# Generated by Django 3.1.2 on 2020-11-28 12:52

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='nombre y apellido')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('edad', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
    ]
